### ISSUE TITLE
 supporting SDXL?

### ISSUE THREAD

**Issue by etwoods** [laksjdjf/IPAdapter-ComfyUI#1]
really awesome work thank guys for that

do you have a plan for supporting SDXL?

**Comment by etwoods** [comment]
https://github.com/tencent-ailab/IP-Adapter
the IP-Adapter has release an version for SDXL

**Comment by laksjdjf** [comment]
I'm currently working on it.

**Comment by etwoods** [comment]
> I'm currently working on it.

Thanks a lot!

**Comment by killporter** [comment]
waiting for it! hopefully is not gonna need a lot of changes

**Comment by laksjdjf** [comment]
I probably did it. ^^^^^^

**Comment by killporter** [comment]
> I probably did it. ^^^^^^

great! i'll test it out immediately

**Comment by killporter** [comment]
tried with searge as well:
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
left over keys: dict_keys(['cond_stage_model.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
loading new
loading new
loading new
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
loading new
unload clone 3
  0% 0/24 [00:00<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL/modules/sampling.py", line 198, in sample
    base_result = nodes.common_ksampler(base_model, noise_seed, steps, cfg, sampler_name, scheduler, base_positive, base_negative, input_latent, denoise=denoise, disable_noise=False, start_step=start_at_step, last_step=base_steps, force_full_denoise=True)
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1176, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/drive/MyDrive/ComfyUI/comfy/sample.py", line 93, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 733, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/sampling.py", line 580, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/k_diffusion/external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/sampler/Fooocus/patch.py", line 296, in sampling_function_patched
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat,
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/sampler/Fooocus/patch.py", line 266, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, **c).chunk(batch_chunks)
  File "/content/drive/MyDrive/ComfyUI/comfy/model_base.py", line 61, in apply_model
    return self.diffusion_model(xc, t, context=context, y=c_adm, control=control, transformer_options=transformer_options).float()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/sampler/Fooocus/patch.py", line 321, in unet_forward_patched
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-animatediff/animatediff/nodes.py", line 37, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/ldm/modules/attention.py", line 695, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/ComfyUI/comfy/ldm/modules/attention.py", line 527, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "/content/drive/MyDrive/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 123, in checkpoint
    return func(*inputs)
  File "/content/drive/MyDrive/ComfyUI/comfy/ldm/modules/attention.py", line 624, in _forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 158, in forward
    q, k, v, ip_k, ip_v = map(
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 159, in <lambda>
    lambda t: t.view(b, -1, extra_options["n_heads"], extra_options["dim_head"]).transpose(1, 2),
RuntimeError: shape '[2, -1, 12, 64]' is invalid for input of size 5120

Prompt executed in 173.52 seconds
[workflow.txt](https://github.com/laksjdjf/IPAdapter-ComfyUI/files/12381533/workflow.txt)

**Comment by killporter** [comment]
with searge again:
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
loading new
100% 24/24 [00:20<00:00,  1.15it/s]
loading new
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL/modules/sampling.py", line 199, in sample
    return nodes.common_ksampler(refiner_model, noise_seed + noise_offset, steps, cfg, sampler_name, scheduler, refiner_positive, refiner_negative, base_result[0], denoise=denoise * refiner_strength, disable_noise=False, start_step=base_steps, last_step=steps, force_full_denoise=True)
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1176, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/content/drive/MyDrive/ComfyUI/comfy/sample.py", line 81, in sample
    comfy.model_management.load_models_gpu([model] + models, comfy.model_management.batch_area_memory(noise.shape[0] * noise.shape[2] * noise.shape[3]))
  File "/content/drive/MyDrive/ComfyUI/comfy/model_management.py", line 368, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "/content/drive/MyDrive/ComfyUI/comfy/model_management.py", line 259, in model_load
    raise e
  File "/content/drive/MyDrive/ComfyUI/comfy/model_management.py", line 255, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "/content/drive/MyDrive/ComfyUI/comfy/sd.py", line 404, in patch_model
    self.model.to(device_to)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 14.52 GiB
Requested               : 81.00 MiB
Device limit            : 14.75 GiB
Free (according to CUDA): 4.81 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

**Comment by xiaoyan1995** [comment]
The latest SDXL version has a black final image and I wonder if there is a recommended workflow?

**Comment by laksjdjf** [comment]
Since clip_vision_g is quite large, could that be the cause?

**Comment by killporter** [comment]
> Since clip_vision_g is quite large, could that be the cause?

could be but i feel a little stuck on this

**Comment by Linaghan34** [comment]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
这个问题有遇到吗大家，尺寸不匹配，我换了1.5和SDXL的都不行

**Comment by Linaghan34** [comment]
![image](https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/127322778/55db32fa-5665-43a0-ba3f-36a3a364a8a9)

**Comment by laksjdjf** [comment]
> raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]). 这个问题有遇到吗大家，尺寸不匹配，我换了1.5和SDXL的都不行

did you use models for [sdxl](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models)?

**Comment by Linaghan34** [comment]
> > 引发运行时错误（'加载 {}：\n\t{} 的state_dict中的错误。format（ 运行时错误：重新采样器加载state_dict时出错：proj_in的大小不匹配.weight：使用形状火炬复制参数。尺寸（[768， 1280]）从检查点开始，当前模型中的形状是割炬。大小（[768， 1664]）.这个问题有遇到吗大家，尺寸不匹配，我换了1.5和SDXL的都不行
> 
> 您是否使用 [SDXL](https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models) 模型？

是我更新了不稳定的controlnet插件，导致的，后面就正常了，感谢回复
