### ISSUE TITLE
New install, never gets to KSampler stage, error "object has no attribute 'patcher'

### ISSUE THREAD

**Issue by Benjamin1973** [laksjdjf/IPAdapter-ComfyUI#24]
Error:

Traceback (most recent call last):
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  [Previous line repeated 1 more time]
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 157, in adapter
    cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
  File "Y:\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 224, in clip_vision_encode
    comfy.model_management.load_model_gpu(clip_vision.patcher)
AttributeError: 'ClipVisionModel' object has no attribute 'patcher'

**Comment by laksjdjf** [comment]
did you use latest version of ComfyUI?
