### ISSUE TITLE
ip-adapter_sdxl_vit-h.bin Error

### ISSUE THREAD

**Issue by hben35096** [laksjdjf/IPAdapter-ComfyUI#30]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 163, in adapter
    self.ipadapter = IPAdapterModel(
  File "/mnt/workspace/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 103, in __init__
    self.image_proj_model.load_state_dict(state_dict["image_proj"])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
	size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 1280]).

![image](https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/139383150/082c1222-b3d9-409c-95f3-c12164e7a76d)

Model download address:
https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models

**Comment by laksjdjf** [comment]
This model  use CLIP_VISION for SDv15.
