### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'patcher'

### ISSUE THREAD

**Issue by easeclick** [laksjdjf/IPAdapter-ComfyUI#47]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
    cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 229, in clip_vision_encode
    comfy.model_management.load_model_gpu(clip_vision.patcher)
                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'patcher'

**Comment by laksjdjf** [comment]
please update comfyui

**Comment by TitusHora** [comment]
I have updated both comfyui and all the plugins, and I am still getting this error message: 'ClipVisionModel' object has no attribute 'processor'

**Comment by chrisprojs** [comment]
i stilll get the same error, even i already update it

**Comment by TitusHora** [comment]
> i stilll get the same error, even i already update it

I fixed the issue by downloading the .safetensors version of IPAdapter Plus from Huggingface.

**Comment by Wukong1-137** [comment]
Im also getting the 'patcher' error. Everything is updated, have tried with multiple WFs. I assumed it was something I was doing wrong and so have been trying for days with different options but I keep coming up with this error.

Has anyone figured out what is going wrong here?

**Comment by pmcdougal** [comment]
`Error occurred when executing IPAdapter:

'NoneType' object has no attribute 'patcher'

  File "G:\Clean AI\ComfyUI fresh\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Clean AI\ComfyUI fresh\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Clean AI\ComfyUI fresh\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Clean AI\ComfyUI fresh\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
    cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Clean AI\ComfyUI fresh\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 229, in clip_vision_encode
    comfy.model_management.load_model_gpu(clip_vision.patcher)
                                          ^^^^^^^^^^^^^^^^^^^`

Getting the same error on a clean install on the latest version of ComfyUI. Trying to follow the SDXL reposer workflow from https://github.com/nerdyrodent/AVeryComfyNerd but am unable.
